feature: ajoute une implémentation de forum dans le backend (models, repository, service, controller)
les-webdevs/refonte-implicaction pull request #2
Opened 2022-11-27 19:17 UTC by Vahelnir

2022-12-03 20:32 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/forum/TopicRepository.java
> +    // TODO: use criteria to order depending on a parameter
Pas sûr de comprendre cet notion de order. Si c'est sort, vous avez le queryParam `sortBy` de votre requête qui va vous permettre de trier les résultats en fonction de sa valeur. Exemple: si sortBy vaut 'id' (valeur par défaut), les résultats seront triés par Id, s'il vaut `createdAt` ça sera par date de création. Ceci couplé à l'attribut sortOrder qui prend potentiellement 2 valeurs, ASC ou DESC, vous avez votre système de tri.

2022-12-03 20:53 UTC, Vahelnir commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/forum/TopicRepository.java
> +    // TODO: use criteria to order depending on a parameter
C'est exactement ca, du coup ce commentaire va pouvoir dégager, merci !

2022-12-03 21:09 UTC, matthieuaudemard requested changes
Juste une ou deux p'tite modif 👍

2022-12-03 21:09 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/forum/CategoryDTO.java
> +public class CategoryDTO {
```suggestion
public class CategoryDto {
```
J'vais être un p'tit peu casse couille question naming dsl 😉 juste histoire de garder de la cohérence.

2022-12-03 21:09 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/forum/ResponseDTO.java
> +public class ResponseDTO {
```suggestion
public class ResponseDto {
```

2022-12-03 21:09 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/forum/TopicDTO.java
> +public class TopicDTO {
```suggestion
public class TopicDto {
```

2022-12-03 21:09 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/forum/CategoryService.java
> +    }
Elle mériterait un p'tit TU celle là 😅 ou au moins quelques commentaires.

2022-12-04 13:42 UTC, cosiewicz commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/forum/CategoryDTO.java
> +public class CategoryDTO {
D'accord ça va être fait 🙂

2022-12-04 13:44 UTC, cosiewicz commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/forum/CategoryService.java
> +    }
Que veut dire "TU" ?

2022-12-04 17:29 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/forum/CategoryService.java
> +    }
Test Unitaire

2022-12-04 17:30 UTC, cosiewicz commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/forum/CategoryService.java
> +    }
Ah ! d'accord merci

2022-12-04 17:34 UTC, Vahelnir commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/forum/CategoryService.java
> +    }
Ouais des commentaires c'est bien aussi pour le moment, les TU on verra à la fin quand on maitrisera la techno correctement parce que pas trop le temps pour le moment :sweat:

2022-12-07 14:43 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/forum/Category.java
> +public class Category {
Pour éviter toute ambiguïté, ou tout refacto ultérieur, je pense qu'il peut être interressant de renommer cette classe en ForumCategory ou PostCategory en fonction de comment vous voyez le truc.

2022-12-07 14:45 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/forum/Response.java
> +public class Response {
Un peu dans le même esprit que pour Category, Response c'est un peu trop vague. C'est une réponse de l'api ? (j'ai appelé certains dto **Request, pourquoi pas imaginer **Response) donc je préfixerais bien cette le nom de cette classe par Forum ou Post, à votre guise.

2022-12-07 15:29 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/forum/CategoryService.java
> +                .collect(Collectors.toList());
Vous allez dire que je suis casse-couille (et je plaide coupable), mais savoir commenter c'est aussi important que de savoir coder. Je vous recommande d'ailleurs le livre [Clean Code](https://www.amazon.fr/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) qui dédie un de ses chapitres aux bons et mauvais commentaires. (je l'ai quelque part en pdf, on peut s'arranger 🤑)

clairement :   `.map(categoryAdapter::toDto) // transforme tous les modeles en DTO` c'est redondant, parce que c'est ce qui est écrit mot pour mot en Java.

En revanche, vos commentaires sur la liste des catégories filles est interressant, même si je ferai volontier un p'tit refacto du type : 

```java
.peek(categoryDto -> {
    // on remplie, pour chaque catégorie, la liste de ses filles
    if (categoryMap.constains(categoryDto.getParentId())) {
        parentCategory.getChildren().add(categoryDto);
    }
})
```
En plus de ça il manque un commentaire à la méthode. Quelque chose du genre :
```
/**
    @return l'ensemble des catégories "mères" (ou trouver un qualificatif plus adéquat) en construisant l'arbre de filiation des sous catégories. 
*/
public List<CategoryDto> getCategories()
```
Un truc comme ça.

2022-12-07 16:05 UTC, matthieuaudemard reviewed
Désolé je vous ai rajouté quelques commentaires sur des trucs que j'avais laissé passé.

Pour ma décharge, votre PR est très très grosse. Pourquoi ? Parce qu'elle n'est pas directement reliée à une US. 

Si vous aviez uniquement une US dont le besoin fonctionnel est de seulement récupérer toutes les catégories de votre forum vous auriez forcément une PR mieux bornée et plus concise, donc une relecture plus facile

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/forum/ResponseService.java
> +    AuthService authService;
Pour que l'injection de dépendance par constructeur fonctionne, vous devez définir ces classes en `private final` en théorie. Sinon j'ai peur que vous ayez un jolie NPE.

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/forum/TopicService.java
> +    private TopicAdapter topicAdapter;
final

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/forum/CategoryAdapter.java
> +        }
```suggestion
        .parentId(model.getParent() != null ? model.getParent().getId() : null)
```

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/forum/CategoryAdapter.java
> +        }
```suggestion
        .parentId(model.getParent() != null ? model.getParent().getId() : null)
```

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/forum/CategoryAdapter.java
> +        }
Vous avez normalement accès à CollectionUtils.isNotEmpty() qui est null safe.
```suggestion
         .children(CollectionUtils.isNotEmpty(model.getChildren()) ? 
                 model.getChildren().stream().map(this::toDtoWithChildren).collect(toList())) :
                 new ArrayList<>() // ou Collections.emptyList() qui fournit une liste déjà instanciée MAIS non mutable
         )
```
De manière générale, il est souvent intéressant d'importer de manière static un membre static d'une classe (sur intelliJ il suffit de d'appuyer sur alt-enter et de cliquer sur 'add static import for ..... ' en ayant positionné le curseur sur le membre static en question). Ca vous permet de gagner en lisibilité.

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +@RequestMapping("/api/forum")
Même si sur les contrôleurs les plus anciens on procédait également avec des Path écris en dur, je préfèrerais que vous déclariez une constante associée dans la classe  utils.ApiUrls pour chacun des paths que vous avez défini 👍

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +    @GetMapping("/categories")
constante ici 🙏

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +    @PostMapping("/categories")
constante ici 🙏

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +    @GetMapping("/categories/{categoryId}")
constante ici 🙏

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +    @GetMapping("/categories/{categoryId}/topics") // NEED TO VALIDATE
constante ici 🙏

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +    @PostMapping("/topics")
constante ici 🙏

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +    @GetMapping("/topics/{topicId}")
constante ici 🙏

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +    @GetMapping("/responses/{topicId}") // NEED TO VALIDATE
constante ici 🙏

2022-12-07 16:05 UTC, matthieuaudemard commented on backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/forum/ForumController.java
> +    @PostMapping("/responses")
constante ici 🙏

2022-12-28 17:30 UTC, cosiewicz reviewed
C'est good 👍

2022-12-28 17:31 UTC, cosiewicz approved these changes
C'est re good 👍

2022-12-28 17:31 UTC, merged